#!/usr/bin/python
## last.py for  in /home/ravane_a/stage/cq-stage/reseau250
##
## Made by 
## Login   <ravane_a@epitech.net>
##
## Started on  Wed Apr 30 09:40:15 2014 
## Last update Wed Apr 30 09:40:33 2014 
##

print("GREATJOB")
